# partA

In [110]:
import pandas as pd

In [111]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,accuracy_score,mean_squared_error,precision_score,recall_score,confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [112]:
data = pd.read_csv("house_price_analysis.csv")
df= pd.DataFrame(data)

In [113]:
df.head(5)

   Area  Bedrooms  Bathrooms  Age  Parking  LocationScore    Price
0   900         2          1   10        1              6  3200000
1  1100         2          2    8        1              7  4200000
2  1400         3          2    6        1              8  5500000
3  1600         3          3    5        2              9  6800000
4  1800         4          3    4        2              9  7600000

In [114]:
df.shape

(15, 7)

In [115]:
df.columns

Index(['Area', 'Bedrooms', 'Bathrooms', 'Age', 'Parking', 'LocationScore',
       'Price'],
      dtype='object')

In [116]:
df.dtypes

Area             int64
Bedrooms         int64
Bathrooms        int64
Age              int64
Parking          int64
LocationScore    int64
Price            int64
dtype: object

In [117]:
df.isna

<bound method DataFrame.isna of     Area  Bedrooms  Bathrooms  Age  Parking  LocationScore    Price
0    900         2          1   10        1              6  3200000
1   1100         2          2    8        1              7  4200000
2   1400         3          2    6        1              8  5500000
3   1600         3          3    5        2              9  6800000
4   1800         4          3    4        2              9  7600000
5   1000         2          1   12        1              6  3500000
6   1250         3          2    7        1              7  4900000
7   1500         3          2    5        2              8  6100000
8   1700         4          3    3        2              9  7300000
9   2000         4          4    2        3             10  9200000
10   950         2          1   11        1              6  3300000
11  1350         3          2    6        1              8  5200000
12  1550         3          3    4        2              8  6400000
13  1750         4          3    3        2              9  7500000
14  2100         5          4    1        3             10  9800000>

In [118]:
df.drop_duplicates(inplace=True)

In [119]:
df.describe

<bound method NDFrame.describe of     Area  Bedrooms  Bathrooms  Age  Parking  LocationScore    Price
0    900         2          1   10        1              6  3200000
1   1100         2          2    8        1              7  4200000
2   1400         3          2    6        1              8  5500000
3   1600         3          3    5        2              9  6800000
4   1800         4          3    4        2              9  7600000
5   1000         2          1   12        1              6  3500000
6   1250         3          2    7        1              7  4900000
7   1500         3          2    5        2              8  6100000
8   1700         4          3    3        2              9  7300000
9   2000         4          4    2        3             10  9200000
10   950         2          1   11        1              6  3300000
11  1350         3          2    6        1              8  5200000
12  1550         3          3    4        2              8  6400000
13  1750         4          3    3        2              9  7500000
14  2100         5          4    1        3             10  9800000>

# partc

In [120]:
df

    Area  Bedrooms  Bathrooms  Age  Parking  LocationScore    Price
0    900         2          1   10        1              6  3200000
1   1100         2          2    8        1              7  4200000
2   1400         3          2    6        1              8  5500000
3   1600         3          3    5        2              9  6800000
4   1800         4          3    4        2              9  7600000
5   1000         2          1   12        1              6  3500000
6   1250         3          2    7        1              7  4900000
7   1500         3          2    5        2              8  6100000
8   1700         4          3    3        2              9  7300000
9   2000         4          4    2        3             10  9200000
10   950         2          1   11        1              6  3300000
11  1350         3          2    6        1              8  5200000
12  1550         3          3    4        2              8  6400000
13  1750         4          3    3        2              9  7500000
14  2100         5          4    1        3             10  9800000

In [121]:
x=df[["Area"]]
y=df["Price"]

In [122]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [123]:
model=LinearRegression()
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc1= r2_score(y_test,pre)

In [124]:
acc

0.9945285670340245

In [125]:
x1=df.drop("Price",axis=1)

In [126]:
y1=df["Price"]

In [127]:
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.2,random_state=42)
model1=LinearRegression()
model1.fit(x_train,y_train)
pre1=model1.predict(x_test)
acc2= r2_score(y_test,pre1)

In [128]:
acc1

0.9906476551249069

In [129]:

poly=PolynomialFeatures(degree=3)
x_poly_train=poly.fit_transform(x_train)
x_poly_test=poly.transform(x_test)

model=LinearRegression()
model.fit(x_poly_train,y_train)
pre=model.predict(x_poly_test)
pre

acc3=r2_score(y_test,pre)
print(acc)
mse=mean_squared_error(y_test,pre)
print(mse)

0.9945285670340245
34044471788.291973

# partD

In [130]:
import numpy as np

In [131]:
df["n_price"]=np.where((df["Price"]>df["Price"].median()),1,0)

In [132]:
df

    Area  Bedrooms  Bathrooms  Age  Parking  LocationScore    Price  n_price
0    900         2          1   10        1              6  3200000        0
1   1100         2          2    8        1              7  4200000        0
2   1400         3          2    6        1              8  5500000        0
3   1600         3          3    5        2              9  6800000        1
4   1800         4          3    4        2              9  7600000        1
5   1000         2          1   12        1              6  3500000        0
6   1250         3          2    7        1              7  4900000        0
7   1500         3          2    5        2              8  6100000        0
8   1700         4          3    3        2              9  7300000        1
9   2000         4          4    2        3             10  9200000        1
10   950         2          1   11        1              6  3300000        0
11  1350         3          2    6        1              8  5200000        0
12  1550         3          3    4        2              8  6400000        1
13  1750         4          3    3        2              9  7500000        1
14  2100         5          4    1        3             10  9800000        1

In [133]:
from sklearn.neighbors import KNeighborsClassifier

In [134]:
x=df.drop("n_price",axis=1)

In [135]:
y=df["n_price"]

In [136]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [137]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc= r2_score(y_test,pre)

In [138]:
acc

1.0

In [139]:
con=confusion_matrix(y_test,pre)

In [140]:
con

array([[2, 0],
       [0, 1]])

In [141]:
recall=recall_score(y_test,pre)

In [142]:
recall

1.0

In [143]:
from sklearn.tree import DecisionTreeClassifier

In [144]:
x=df.drop("n_price",axis=1)

In [145]:
y=df["n_price"]

In [146]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [147]:
model= DecisionTreeClassifier(criterion="entropy")

In [148]:
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc= r2_score(y_test,pre)

In [149]:
acc

1.0

In [150]:
d={
    "Model":["Simple LR","Multiple LR","Polynomial"],
    "R2":[acc1,acc2,acc3]
}

In [151]:
d1=pd.DataFrame(d)

In [152]:
d1

         Model        R2
0    Simple LR  0.990648
1  Multiple LR  0.998118
2   Polynomial  0.994529

In [166]:
data = pd.read_csv("Churn.csv")
df1=pd.DataFrame(data)

In [167]:
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [168]:
x=df1.drop(columns=["customerID","Churn"],axis=1)

In [169]:
y=df1["Churn"]

In [170]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [172]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'Female'